theme:           jekyll-theme-cayman
title:           Fireworks
description:     Create your own fireworks show or watch one randomly
is_user_page:    false
is_project_page: true
show_downloads:  true
